name = "reserva-auditorio"
main = "src/worker.js"
compatibility_date = "2026-05-03"

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "RESERVAS_DB"
database_name = "reserva-auditorio-db"
database_id = "47e1a185-49c6-479b-a845-a28179556bd0"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "ADMIN_LOGIN_KV"
id = "63a1fa420ca74538a6904d56f81eb8d8"
